FROM ubuntu:trusty

#Default branch name master
ARG BRANCH_NAME=master
#Default
ARG REPO_SLUG=duality-solutions/dynamic
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY dynamic.tar.gz /dynamic.tar.gz
RUN tar -xvf /dynamic.tar.gz

#xenial
#Missing requirement: libtool
#RUN apt install -yqq libtool-bin
RUN cd /dynamic/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /dynamic && scripts/windows-crosscompile/compile-dynamic.sh
