// Copyright (c) 2016-2018 Duality Blockchain Solutions Developers
// Copyright (c) 2014-2018 The Dash Core Developers
// Copyright (c) 2009-2018 The Bitcoin Developers
// Copyright (c) 2009-2018 Satoshi Nakamoto
// Distributed under the MIT/X11 software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#ifndef DYNAMIC_CHAINPARAMSSEEDS_H
#define DYNAMIC_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the Dynamic network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */

//	Dynamic Seeds
static SeedSpec6 pnSeed6_main[] = {};

static SeedSpec6 pnSeed6_test[] = {};

#endif // DYNAMIC_CHAINPARAMSSEEDS_H
